### ISSUE TITLE
unrecognized command line option "--E" when enabling skip_preprocessor

### ISSUE THREAD

**Issue by BaderEddineOuaich** [deep5050/cppcheck-action#16]
Hello there,
Thanks again for this useful tool!
I had an issue running with skip_preprocessor option enabled, it adds an option --E which is not recognized by cppcheck.
here some info may help fixing this issue:
<strong>Logs</strong>
<pre>
<strong>cppcheck</strong>
Run deep5050/cppcheck-action@main
  with:
    github_token: ***
    skip_preprocessor: enable
    enable: all
    exclude_check: ./Dependencies/
    force_language: c++
    max_ctu_depth: 9
    output_file: ./CppCheck-Static-Analysis-Report.txt
    check_library: disable
    inconclusive: enable
    inline_suppression: disable
    platform: disable
/usr/bin/docker run --name c0654dccb4854943dbf8bf480d7be_9f9d24 --label 179394 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_SKIP_PREPROCESSOR -e INPUT_ENABLE -e INPUT_EXCLUDE_CHECK -e INPUT_FORCE_LANGUAGE -e INPUT_MAX_CTU_DEPTH -e INPUT_OUTPUT_FILE -e INPUT_CHECK_LIBRARY -e INPUT_INCONCLUSIVE -e INPUT_INLINE_SUPPRESSION -e INPUT_PLATFORM -e INPUT_TARGET_BRANCH -e INPUT_PULL_REQUEST_BRANCH -e INPUT_TARGET_REPOSITORY -e INPUT_PULL_REQUEST_REPOSITORY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Enigma/Enigma":"/github/workspace" 179394:684c0654dccb4854943dbf8bf480d7be
Cppcheck 2.3
cppcheck: error: unrecognized command line option: "--E".
given command cppcheck  --E --enable=all -i ./Dependencies/ --inconclusive --language=c++ --max-ctu-depth=9 --output-file=./CppCheck-Static-Analysis-Report.txt .
checking version
</pre>
[Action Link](https://github.com/BaderEddineOuaich/Enigma/runs/1539683996)

**Comment by deep5050** [comment]
I'll be checking this ASAP

**Comment by deep5050** [comment]
actually, the new version has changed some of the options. please let me know if this works and report any further issues.

**Comment by BaderEddineOuaich** [comment]
Works now 🎉!  
thanks again for the effort!

**Comment by deep5050** [comment]
@all-contributors please add @BaderEddineOuaich  for tests
