### ISSUE TITLE
Have report fail build instead of committing reports to repo

### ISSUE THREAD

**Issue by DomAmato** [deep5050/cppcheck-action#3]
It would be more useful for the action to dump the error report to the the console and if there are errors to fail the action. Commiting the reports to the repo is less helpful since it won't fail the action and is inconsistent with other CI workflows.

**Comment by deep5050** [comment]
Hi, @DomAmato thanks for submitting the issue. New release 1.1.1 fixed this :)

**Comment by deep5050** [comment]
@all-contributors please add @DomAmato  for infrastructure

**Comment by deep5050** [comment]
@all-contributors please add @DomAmato for infrastructure
