### ISSUE TITLE
feature request: configurable commit message / details

### ISSUE THREAD

**Issue by bmahlbrand** [deep5050/cppcheck-action#4]
I'd really like to have more control over the commit messages in this action, for example in a clang-format action I use, this is how they expose the parameters.

        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'

Does this seem like something worth integrating?

**Comment by deep5050** [comment]
Hi @bmahlbrand , sounds cool to me, indeed it would be a great feature, but the problem is I'm having a busy schedule. I'm not sure if I could manage time to work for this repo. I'll definitely add this feature once I have some time. 👍
